#ddev-generated
# MinIO addon for DDEV
services:
  minio:
    container_name: ddev-${DDEV_SITENAME}-minio
    image: minio/minio:latest
    restart: "no"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    expose:
      - "25252:25252"
      - "9000:9000"
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - type: "volume"
        source: minio
        target: "/mnt/data"
        volume:
          nocopy: true
      - "./minio/config.env:/etc/config.env"
      - ".:/mnt/ddev_config"
    environment:
      - MINIO_CONFIG_ENV_FILE=/etc/config.env
      - MINIO_BROWSER_REDIRECT_URL=${DDEV_PRIMARY_URL}:8090
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8089:25252
      - HTTPS_EXPOSE=8090:25252
    healthcheck:
      interval: 120s
      timeout: 2s
      retries: 1

    command:
      - minio
      - server
      - --address
      - :9000
      - --console-address
      - :25252

volumes:
  minio:
