#ddev-generated
# Simple template to demonstrate addon-template
services:
  addon-template:
    container_name: ddev-${DDEV_SITENAME}-minio
    image: minio/minio
    networks: [default, ddev_default]
    restart: "no"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
      - ".:/mnt/ddev_config"
      - "./minio/config.env:/etc/config.env"
      - "./minio/data:/mnt/data"
    environment:
      HTTP_EXPOSE: 8090:9090
      HTTPS_EXPOSE: 8090:9090
      MINIO_CONFIG_ENV_FILE: /etc/config.env
      MINIO_SERVER_URL: ${DDEV_HOSTNAME}:8090

    command:
      - "minio"
      - "server"
      - '--console-address ":9090"'
