name: "Test DDEV Addon"
on:
  pull_request:
    paths-ignore:
      - "README.md"
      - ".github/workflows/*.yml"
  merge_group:

jobs:
  run_tests:
    name: Run tests
    uses: oblakstudio/public-workflows/.github/workflows/ddev-test_addon.yaml@v1
    secrets: inherit
    with:
      test_type: "local"
      os: '["ubuntu-latest"]'
