name: "Test DDEV Addon"
on:
  pull_request:
  merge_group:

jobs:
  run_tests:
    name: Run tests
    uses: oblakstudio/public-workflows/.github/workflows/ddev/test_ddev_addon.yaml@v1
    secrets: inherit
    with:
      test_type: "local"
